### ISSUE TITLE
Problema "traduciendo" tweemanager

### ISSUE THREAD

**Issue by cperales** [nfqsolutions/nfq#2]
Estoy implementando tweemanager desde el estilo que tenemos ahora al de NFQ, siguiendo este repositiro, en la rama tweenfq.

Después de desinstalar el antiguo tweemanager del entorno virtual y volverlo a instalar, me da este problema:

```bash
Traceback (most recent call last):
  File "/home/cperales/abanca/.env/bin/tweemanager", line 11, in <module>
    load_entry_point('tweemanager==0.1.0', 'console_scripts', 'tweemanager')()
  File "/home/cperales/abanca/.env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/cperales/abanca/.env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'tweemanager') not found
```

He pensado que puede ser que setuptools no esté actualizado, pero ya lo he actualizado con `pip --upgrade` y sigue dándome error.

**Comment by cperales** [comment]
Se trataba de un problema al intentar ejecutar un script. Hay que añadir "scripts" o "entry_point" al setup.py
